import type { ConfigDefinition, WorldState } from "../shared/types.js";

export const CONFIG_DEFINITIONS: ConfigDefinition[] = [
  { key: "simulation.tick_ms", category: "simulation", description: "Milliseconds between live simulation ticks.", type: "number", defaultValue: 1000, min: 250, max: 10000 },
  { key: "simulation.shift_minutes", category: "simulation", description: "Length of a work shift in minutes.", type: "number", defaultValue: 360, min: 1, max: 1440 },
  { key: "simulation.offline_max_hours", category: "simulation", description: "Maximum downtime applied on restart.", type: "number", defaultValue: 6, min: 0, max: 168 },
  { key: "moon.base_fall_rate", category: "moon", description: "Passive lunar descent per second.", type: "number", defaultValue: 0.0018, min: 0, max: 1 },
  { key: "moon.force_decay", category: "moon", description: "Haul force lost per second.", type: "number", defaultValue: 0.08, min: 0, max: 1 },
  { key: "moon.maximum_altitude", category: "moon", description: "Maximum displayed Moon altitude.", type: "number", defaultValue: 100, min: 10, max: 10000 },
  { key: "winch.haul_power", category: "winch", description: "Base force generated by !haul.", type: "number", defaultValue: 0.022, min: 0.001, max: 2 },
  { key: "winch.brace_power", category: "winch", description: "Cable tension removed by !brace.", type: "number", defaultValue: 4, min: 0, max: 50 },
  { key: "boiler.fuel_per_tick", category: "boiler", description: "Fuel consumed each second while operating.", type: "number", defaultValue: 0.012, min: 0, max: 10 },
  { key: "boiler.heat_per_fuel", category: "boiler", description: "Heat produced by burning fuel.", type: "number", defaultValue: 0.018, min: 0, max: 5 },
  { key: "cooling.coolant_efficiency", category: "cooling", description: "Heat removed per unit of coolant.", type: "number", defaultValue: 2.2, min: 0, max: 20 },
  { key: "player.max_stamina", category: "player", description: "Base maximum worker stamina.", type: "number", defaultValue: 100, min: 10, max: 1000 },
  { key: "player.stamina_regen", category: "player", description: "Stamina restored per second.", type: "number", defaultValue: 0.45, min: 0, max: 100 },
  { key: "player.action_cooldown_ms", category: "player", description: "Minimum time between useful actions.", type: "number", defaultValue: 1800, min: 0, max: 60000 },
  { key: "player.haul_stamina_cost", category: "player", description: "Stamina cost of !haul.", type: "number", defaultValue: 10, min: 0, max: 100 },
  { key: "player.base_action_power", category: "player", description: "Base multiplier for all workers.", type: "number", defaultValue: 1, min: 0.1, max: 10 },
  { key: "player.max_level_bonus", category: "player", description: "Maximum veteran effectiveness bonus.", type: "number", defaultValue: 0.5, min: 0, max: 1 },
  { key: "player.window_contribution_cap", category: "player", description: "Useful contribution allowed per ten seconds.", type: "number", defaultValue: 60, min: 1, max: 1000 },
  { key: "events.minimum_interval", category: "events", description: "Minimum seconds between events.", type: "number", defaultValue: 600, min: 15, max: 86400 },
  { key: "events.maximum_interval", category: "events", description: "Maximum seconds between events.", type: "number", defaultValue: 1500, min: 30, max: 86400 },
  { key: "events.default_duration", category: "events", description: "Default command window duration in seconds.", type: "number", defaultValue: 45, min: 5, max: 600 },
  { key: "autopilot.enabled", category: "autopilot", description: "Enable the municipal skeleton crew.", type: "boolean", defaultValue: true },
  { key: "autopilot.efficiency", category: "autopilot", description: "Skeleton crew effectiveness.", type: "number", defaultValue: 0.34, min: 0, max: 1 },
  { key: "autopilot.minimum_altitude", category: "autopilot", description: "Altitude the skeleton crew attempts to defend.", type: "number", defaultValue: 24, min: 1, max: 100 },
  { key: "backups.interval_hours", category: "backups", description: "Automatic snapshot interval; zero disables it.", type: "number", defaultValue: 6, min: 0, max: 168 },
];

export type GameConfig = Record<string, number | boolean | string>;

export const defaultConfig = (): GameConfig => Object.fromEntries(CONFIG_DEFINITIONS.map((item) => [item.key, item.defaultValue]));

export const freshWorld = (now = new Date()): WorldState => ({
  moon: { altitude: 64.8, targetAltitude: 90, velocity: -0.003, haulProgress: 0, instability: 8, massModifier: 1, anomalyLevel: 2, temporaryScale: 1, secondMoon: false },
  machine: { integrity: 82, heat: 47, pressure: 51, power: 68, cableTension: 43, lubrication: 72, efficiency: 78 },
  resources: { fuel: 8420, coolant: 2781, scrap: 614, spareParts: 180, electricity: 930, moonlight: 3 },
  world: { currentShift: 1, shiftStartedAt: now.toISOString(), totalShiftsSurvived: 0, totalDistanceHauled: 0, disastersSurvived: 0, workersLost: 0, anomalyLevel: 2, morale: 70, treasury: 2500, catastropheCount: 0, daysSinceIncident: 0 },
  tick: 0,
  paused: false,
  pausedAt: null,
  lastTickAt: now.toISOString(),
  nextEventAt: new Date(now.getTime() + 10 * 60_000).toISOString(),
  activeEvent: null,
  currentHaulForce: 0,
  recentActions: [{ at: now.toISOString(), kind: "system", text: "Night shift clocked in. The Moon declined to comment." }],
  currentAlert: null,
  milestone: null,
});
