import { PageHeader, Shell } from "../components";

export function AboutPage() { return <Shell active="/about"><PageHeader eyebrow="EMPLOYEE HANDBOOK / REVISION 38-B" title="The Moon will not move itself." description="Something broke gravity. The city put Twitch chat on the night shift."/><section className="handbook-grid">
  <article className="panel handbook-intro"><span className="big-number">01</span><h2>Read the active order</h2><p>The stream always shows the most useful command. Type it in Twitch chat during work windows, emergencies, and events.</p></article>
  <article className="panel"><span className="big-number">02</span><h2>Do useful work</h2><p><code>!haul</code> moves the Moon. <code>!stoke</code> powers the machine. <code>!cool</code> prevents paperwork-generating explosions. <code>!tune</code> asks the Signal Room to improve efficiency.</p></article>
  <article className="panel"><span className="big-number">03</span><h2>Become employable</h2><p>Your worker persists across shifts. Useful actions earn experience, pay, titles, commendations, minor injuries, and a defensible amount of Moon-hauling credit.</p></article>
  <article className="panel"><span className="big-number">04</span><h2>Fail productively</h2><p>There is no permanent game over. Disasters damage the machine, mutate the world, and leave scars. If the Moon reaches the ground, reconstruction begins immediately.</p></article>
  <aside className="panel command-reference"><div className="section-head"><span>APPROVED BASIC COMMANDS</span></div><div><b>GENERAL</b><code>!join</code><code>!status</code><code>!help</code><code>!work</code></div><div><b>WINCH</b><code>!haul</code><code>!brace</code><code>!release</code><code>!grease</code></div><div><b>BOILER</b><code>!stoke</code><code>!shovel</code><code>!dampen</code></div><div><b>COOLING</b><code>!vent</code><code>!cool</code><code>!flush</code></div><div><b>SIGNAL</b><code>!tune</code><code>!listen</code><code>!signal</code></div></aside>
  <div className="panel handbook-warning"><b>REMEMBER</b><span>Stamina regenerates over time. Many different workers are more valuable than one employee repeatedly striking the same lever.</span></div>
  </section></Shell>; }
